// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk3lx1IgM9W7xfCjnydV0lzq2WI38EGgg',
    appId: '1:293943781208:web:ffbc0d5d30bf1fc71fe72d',
    messagingSenderId: '293943781208',
    projectId: 'vidar-a9f92',
    authDomain: 'vidar-a9f92.firebaseapp.com',
    storageBucket: 'vidar-a9f92.appspot.com',
    measurementId: 'G-86KBWE3RLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQN8szzf8C74zTWMw6_b2u2DqRI-0J-Q',
    appId: '1:293943781208:android:c08fdfcd5b4bdee21fe72d',
    messagingSenderId: '293943781208',
    projectId: 'vidar-a9f92',
    storageBucket: 'vidar-a9f92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1TW7g1ASFUaQCjgSCBwTvxMikMf8ef_Y',
    appId: '1:293943781208:ios:072434b448d3ae781fe72d',
    messagingSenderId: '293943781208',
    projectId: 'vidar-a9f92',
    storageBucket: 'vidar-a9f92.appspot.com',
    iosBundleId: 'com.example.vidarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1TW7g1ASFUaQCjgSCBwTvxMikMf8ef_Y',
    appId: '1:293943781208:ios:66202066a2e6f4a11fe72d',
    messagingSenderId: '293943781208',
    projectId: 'vidar-a9f92',
    storageBucket: 'vidar-a9f92.appspot.com',
    iosBundleId: 'com.example.vidarApp.RunnerTests',
  );
}
